# Generated by Django 4.2 on 2023-04-18 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Apartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Apartment name", max_length=255)),
                (
                    "description",
                    models.TextField(help_text="Enter apartment description"),
                ),
                ("address", models.TextField(help_text="Enter apartment address")),
                ("lga", models.CharField(help_text="LGA", max_length=50)),
                ("city", models.CharField(help_text="City", max_length=50)),
                ("state", models.CharField(help_text="State", max_length=20)),
                ("country", models.CharField(help_text="Country", max_length=50)),
                ("hasOccupants", models.BooleanField(default=False)),
                ("isOccupied", models.BooleanField(default=False)),
                ("price", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ApartmentReviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ApartmentImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image1", models.TextField()),
                ("image2", models.TextField()),
                ("image3", models.TextField()),
                ("image4", models.TextField()),
                ("image5", models.TextField()),
                ("image6", models.TextField()),
                ("image7", models.TextField()),
                ("image8", models.TextField()),
                ("image9", models.TextField()),
                ("image10", models.TextField()),
                (
                    "apartment_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apartment.apartment",
                    ),
                ),
            ],
        ),
    ]
