# Generated by Django 4.2 on 2023-04-25 01:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("apartment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="amenities",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="apartment",
            name="apartment_fees",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="apartment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="apartment",
            name="number_of_occupants",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="apartment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="ApartmentBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=10)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "apartment_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apartment.apartment",
                    ),
                ),
            ],
        ),
    ]
