# Generated by Django 4.2 on 2023-08-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalcharge',
            old_name='charge',
            new_name='name',
        ),
        migrations.AddField(
            model_name='additionalcharge',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
