# Generated by Django 4.2 on 2023-09-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='lease_type',
            field=models.CharField(choices=[('Short Lease', 'Short Lease'), ('Long Lease', 'Long Lease')], default='Long Lease'),
        ),
    ]
