# Generated by Django 4.2 on 2023-08-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0002_rename_charge_additionalcharge_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancellationpolicy',
            name='policy',
            field=models.CharField(max_length=500),
        ),
    ]
