# Generated by Django 4.2 on 2023-09-06 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0002_alter_apartment_lease_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='verification_status',
        ),
    ]
