# Generated by Django 4.2 on 2023-08-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0003_alter_cancellationpolicy_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='lease_type',
            field=models.CharField(choices=[('Short Lease', 'Short Lease'), ('Long Lease', 'Long Lease')], default='Short Lease'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='point_of_interest',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='additionalcharge',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='apartment_type',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='apartmentamenities',
            name='amenity',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='apartmentrules',
            name='rule',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='saftyandsecurity',
            name='item',
            field=models.CharField(max_length=500),
        ),
    ]
