# Generated by Django 4.2 on 2023-09-06 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0003_remove_apartment_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='verification_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Unverified', 'Unverified'), ('Verified', 'Verified')], default='Unverified'),
        ),
        migrations.AlterField(
            model_name='changeapartment',
            name='current_apartment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_apartment_changes', to='apartment.apartment'),
        ),
    ]
