# Generated by Django 4.2 on 2023-08-25 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0004_apartment_lease_type_apartment_point_of_interest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='additional_charges',
        ),
    ]
