# Generated by Django 4.2 on 2023-09-06 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0004_apartment_verification_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeapartment',
            name='current_apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_apartment_changes', to='apartment.apartment'),
        ),
    ]
