# Generated by Django 4.2 on 2023-04-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartment", "0004_apartmentinspection_isinspected"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="total_price",
            field=models.FloatField(default=0),
        ),
    ]
