# Generated by Django 4.2 on 2023-09-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0005_alter_changeapartment_current_apartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='master_bedroom_price',
            field=models.IntegerField(default=0),
        ),
    ]
