# Generated by Django 4.2 on 2023-05-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartment", "0005_apartment_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartmentbooking",
            name="paidFor",
            field=models.BooleanField(default=False),
        ),
    ]
