# Generated by Django 4.2 on 2023-08-25 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0005_remove_apartment_additional_charges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='type_of_space',
        ),
    ]
