# Generated by Django 4.2 on 2023-05-02 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apartment", "0006_apartmentbooking_paidfor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apartmentbooking",
            old_name="paidFor",
            new_name="isPaidFor",
        ),
    ]
