# Generated by Django 4.2 on 2023-09-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0006_apartment_master_bedroom_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentbooking',
            name='paid_for_master_bedroom',
            field=models.BooleanField(default=False),
        ),
    ]
