# Generated by Django 4.2 on 2023-05-08 01:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("apartment", "0007_rename_paidfor_apartmentbooking_ispaidfor"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartmentbooking",
            name="payment_reference",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="apartment",
            name="price",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="total_price",
            field=models.IntegerField(default=0),
        ),
    ]
