# Generated by Django 4.2 on 2023-08-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0007_apartment_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='_occupancy_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
