# Generated by Django 4.2 on 2023-09-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0007_apartmentbooking_paid_for_master_bedroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='master_bedroom_tax_price',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='apartment',
            name='master_bedroom_total_price',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='total_price',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
