# Generated by Django 4.2 on 2023-08-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0008_apartment__occupancy_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='bookings',
            field=models.ManyToManyField(related_name='apartments', to='apartment.apartmentbooking'),
        ),
    ]
