# Generated by Django 4.2 on 2023-09-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0008_apartment_master_bedroom_tax_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalcharge',
            name='amount',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='master_bedroom_price',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='apartmentbooking',
            name='amount_paid',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='cost',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
    ]
