# Generated by Django 4.2 on 2023-05-08 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartment", "0008_apartmentbooking_payment_reference_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartmentinspection",
            name="inspection_date",
            field=models.DateTimeField(),
        ),
    ]
