# Generated by Django 4.2 on 2023-09-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0009_alter_additionalcharge_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='is_master_bedroom_available',
            field=models.BooleanField(default=True),
        ),
    ]
