# Generated by Django 4.2 on 2023-05-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartment", "0009_alter_apartmentinspection_inspection_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartmentimages",
            name="image1",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="apartmentimages",
            name="image10",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="apartmentimages",
            name="image2",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="apartmentimages",
            name="image3",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="apartmentimages",
            name="image4",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="apartmentimages",
            name="image5",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="apartmentimages",
            name="image6",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="apartmentimages",
            name="image7",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="apartmentimages",
            name="image8",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="apartmentimages",
            name="image9",
            field=models.TextField(blank=True, null=True),
        ),
    ]
