# Generated by Django 4.2 on 2023-08-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0009_apartment_bookings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='bookings',
        ),
        migrations.AlterField(
            model_name='apartment',
            name='is_verified',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Unverified', 'Unverified'), ('Verified', 'Verified')], default='Unverified'),
        ),
    ]
