# Generated by Django 4.2 on 2023-09-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0010_apartment_is_master_bedroom_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='status',
            field=models.CharField(choices=[('Listed', 'Listed'), ('Unlisted', 'Unlisted'), ('Pending', 'Pending'), ('Unverified', 'Unverified'), ('Verified', 'Verified'), ('Draft', 'Draft')], default='Unverified', max_length=255),
        ),
    ]
