# Generated by Django 4.2 on 2023-08-28 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0010_remove_apartment_bookings_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='is_verified',
            new_name='verification_status',
        ),
    ]
