# Generated by Django 4.2 on 2023-08-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0011_rename_is_verified_apartment_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'MEdium'), ('High', 'High')], default='Low'),
        ),
    ]
