# Generated by Django 4.2 on 2023-05-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartment", "0011_apartment_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="images",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
