# Generated by Django 4.2 on 2023-08-28 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0012_maintenance_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trancaction_date', models.DateField(auto_now_add=True)),
                ('trancaction_time', models.TimeField(auto_now_add=True)),
                ('expense', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending')),
                ('amount', models.DecimalField(decimal_places=1, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apartment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.apartment')),
            ],
        ),
    ]
