# Generated by Django 4.2 on 2023-09-12 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0012_apartment_owner_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='verification_status',
        ),
    ]
