# Generated by Django 4.2 on 2023-08-28 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0013_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='trancaction_date',
            new_name='transaction_date',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='trancaction_time',
            new_name='transaction_time',
        ),
    ]
