# Generated by Django 4.2 on 2023-05-10 06:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apartment", "0014_alter_apartmentimages_image1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartmentimages",
            name="image1",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="image 1",
            ),
        ),
        migrations.AlterField(
            model_name="apartmentimages",
            name="image10",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="image 10",
            ),
        ),
        migrations.AlterField(
            model_name="apartmentimages",
            name="image2",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="image 2",
            ),
        ),
        migrations.AlterField(
            model_name="apartmentimages",
            name="image3",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="image 3",
            ),
        ),
        migrations.AlterField(
            model_name="apartmentimages",
            name="image4",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="image 4",
            ),
        ),
        migrations.AlterField(
            model_name="apartmentimages",
            name="image5",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="image 5",
            ),
        ),
        migrations.AlterField(
            model_name="apartmentimages",
            name="image6",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="image 6",
            ),
        ),
        migrations.AlterField(
            model_name="apartmentimages",
            name="image7",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="image 7",
            ),
        ),
        migrations.AlterField(
            model_name="apartmentimages",
            name="image8",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="image 8",
            ),
        ),
        migrations.AlterField(
            model_name="apartmentimages",
            name="image9",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="image 9",
            ),
        ),
    ]
