# Generated by Django 4.2 on 2023-09-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0014_alter_apartment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.DecimalField(decimal_places=1, default=10.0, max_digits=10),
        ),
    ]
