# Generated by Django 4.2 on 2023-09-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0014_rename_trancaction_date_service_transaction_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Annual Rent', 'Annual Rent'), ('Maintenance', 'Maintenance')], default='Annual Rent', max_length=30),
        ),
    ]
