# Generated by Django 4.2 on 2023-09-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0015_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_type',
            field=models.CharField(choices=[('Electrical', 'Electrical'), ('Structural', 'Structural'), ('Plumbing', 'Plumbing')], default='Structural', max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Done', 'Done')], default='Pending', max_length=20),
        ),
    ]
