# Generated by Django 4.2 on 2023-05-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartment", "0016_remove_apartment_images_apartment_image1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="number_of_rooms",
            field=models.IntegerField(default=0),
        ),
    ]
