# Generated by Django 4.2 on 2023-05-20 08:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("apartment", "0017_apartment_number_of_rooms"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="apartment_type",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="apartment",
            name="map_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="apartment",
            name="rating",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="apartment",
            name="rules",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="apartment",
            name="tax",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="apartmentreviews",
            name="apartment_id",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="apartment.apartment",
            ),
        ),
        migrations.AddField(
            model_name="apartmentreviews",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="apartmentreviews",
            name="review",
            field=models.TextField(default="review"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="apartmentreviews",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="apartmentreviews",
            name="user",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="apartmentbooking",
            name="user_id",
            field=models.CharField(max_length=255),
        ),
    ]
