# Generated by Django 4.2 on 2023-09-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0017_apartment_is_master_bedroom_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='other_rooms',
            field=models.JSONField(default=dict),
        ),
    ]
