# Generated by Django 4.2 on 2023-05-20 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apartment", "0018_apartment_apartment_type_apartment_map_url_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ApartmentReviews",
            new_name="ApartmentReview",
        ),
    ]
