# Generated by Django 4.2 on 2023-05-20 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apartment", "0019_rename_apartmentreviews_apartmentreview"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apartmentreview",
            old_name="user",
            new_name="user_id",
        ),
    ]
