# Generated by Django 4.2 on 2023-09-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0019_alter_apartment_other_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='master_bedroom_percentage',
            field=models.DecimalField(decimal_places=1, default=0.3, max_digits=10),
        ),
    ]
