# Generated by Django 4.2 on 2023-09-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0020_apartment_master_bedroom_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='master_bedroom_percentage',
            field=models.FloatField(default=0.3),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='master_bedroom_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='master_bedroom_tax_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='master_bedroom_total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='owner_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='tax',
            field=models.FloatField(default=7.5),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='tax_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
