# Generated by Django 4.2 on 2023-05-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartment", "0020_rename_user_apartmentreview_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="amenities",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="apartment_fees",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="rules",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
