# Generated by Django 4.2 on 2023-09-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0021_alter_apartment_master_bedroom_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalcharge',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='apartmentbooking',
            name='amount_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
