# Generated by Django 4.2 on 2023-05-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartment", "0022_alter_apartment_apartment_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="map_url",
            field=models.TextField(blank=True, default="map url", null=True),
        ),
    ]
