# Generated by Django 4.2 on 2023-09-15 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0022_alter_additionalcharge_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartmentbooking',
            old_name='no_of_guests',
            new_name='no_of_rooms',
        ),
    ]
