# Generated by Django 4.2 on 2023-09-19 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0023_rename_no_of_guests_apartmentbooking_no_of_rooms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='other_rooms',
            new_name='rooms',
        ),
    ]
