# Generated by Django 4.2 on 2023-10-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0024_apartmentbooking_rent_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentbooking',
            name='rooms_paid_for',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
