# Generated by Django 4.2 on 2023-05-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartment", "0025_apartmentinspection_inspection_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=10)),
                ("amount", models.CharField(max_length=10)),
                ("transaction_status", models.CharField(max_length=10)),
                ("description", models.CharField(max_length=20)),
                ("recipient", models.CharField(max_length=255)),
                ("payment_method", models.CharField(max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
