# Generated by Django 4.2 on 2023-09-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0025_apartment_single_room_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='accommodation_capacity',
            field=models.IntegerField(default=0),
        ),
    ]
