# Generated by Django 4.2 on 2023-09-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0025_apartment_single_room_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='accommodation_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='map_url',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
