# Generated by Django 4.2 on 2023-05-21 18:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("apartment", "0026_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="payment_reference",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
