# Generated by Django 4.2 on 2023-09-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0026_apartment_accommodation_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
