# Generated by Django 4.2 on 2023-10-13 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0026_alter_apartment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='single_room_price',
            field=models.IntegerField(default=0),
        ),
    ]
