# Generated by Django 4.2 on 2023-05-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartment", "0027_transaction_payment_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartmentreview",
            name="number_of_reviews",
            field=models.IntegerField(default=0),
        ),
    ]
