# Generated by Django 4.2 on 2023-05-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartment", "0029_remove_apartmentreview_number_of_reviews_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartmentreview",
            name="rating",
            field=models.FloatField(default=0.0),
        ),
    ]
