# Generated by Django 4.2 on 2023-05-21 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartment", "0030_apartmentreview_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="rating",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="tax",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="apartmentreview",
            name="rating",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
    ]
