# Generated by Django 4.2 on 2023-05-28 23:18

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("apartment", "0034_alter_apartment_amenities_alter_apartment_rules"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApartmentImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        verbose_name="image",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Maintainance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=20)),
                ("phone_number", models.CharField(max_length=11)),
                ("maintainance_category", models.CharField(max_length=20)),
                ("maintainance_type", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=20)),
                ("description", models.TextField()),
                ("date_of_complaint", models.DateField(auto_now_add=True)),
                ("time_of_complaint", models.TimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="apartment",
            name="image1",
        ),
        migrations.RemoveField(
            model_name="apartment",
            name="image10",
        ),
        migrations.RemoveField(
            model_name="apartment",
            name="image2",
        ),
        migrations.RemoveField(
            model_name="apartment",
            name="image3",
        ),
        migrations.RemoveField(
            model_name="apartment",
            name="image4",
        ),
        migrations.RemoveField(
            model_name="apartment",
            name="image5",
        ),
        migrations.RemoveField(
            model_name="apartment",
            name="image6",
        ),
        migrations.RemoveField(
            model_name="apartment",
            name="image7",
        ),
        migrations.RemoveField(
            model_name="apartment",
            name="image8",
        ),
        migrations.RemoveField(
            model_name="apartment",
            name="image9",
        ),
        migrations.DeleteModel(
            name="ApartmentImages",
        ),
        migrations.AddField(
            model_name="apartmentimage",
            name="apartment_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="apartment.apartment"
            ),
        ),
    ]
