# Generated by Django 4.2 on 2023-05-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartment", "0036_maintainance_cost_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintainance",
            name="status",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Done", "Done")],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
