# Generated by Django 4.2 on 2023-05-30 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartment", "0037_alter_maintainance_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartmentbooking",
            name="amount_paid",
            field=models.IntegerField(default=0),
        ),
    ]
