# Generated by Django 4.2 on 2023-05-31 00:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("apartment", "0038_apartmentbooking_amount_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="transaction_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="transaction_time",
            field=models.TimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
