# Generated by Django 4.2 on 2023-05-31 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartment", "0039_transaction_transaction_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("Annual Rent", "Annual Rent"),
                    ("Maintainance", "Maintainance"),
                ],
                default="Annual Rent",
                max_length=30,
            ),
        ),
    ]
