# Generated by Django 4.2 on 2023-05-31 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartment", "0040_transaction_transaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="description",
            field=models.TextField(default="description"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_status",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Done", "Done")],
                default="Pending",
                max_length=10,
            ),
        ),
    ]
