# Generated by Django 4.2 on 2023-06-01 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartment", "0041_alter_transaction_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apartmentimage",
            name="image",
        ),
        migrations.AddField(
            model_name="apartmentimage",
            name="images",
            field=models.JSONField(blank=True, default={"images": []}, null=True),
        ),
    ]
