# Generated by Django 4.2 on 2023-06-01 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartment", "0042_remove_apartmentimage_image_apartmentimage_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="images",
            field=models.JSONField(blank=True, default={"images": []}, null=True),
        ),
    ]
