# Generated by Django 4.2 on 2023-06-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartment", "0043_apartment_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="amenities",
            field=models.JSONField(blank=True, default=[], null=True),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="images",
            field=models.JSONField(blank=True, default=[], null=True),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="rules",
            field=models.JSONField(blank=True, default=[], null=True),
        ),
    ]
