# Generated by Django 4.2 on 2023-06-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartment", "0044_alter_apartment_amenities_alter_apartment_images_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartmentinspection",
            name="inspection_time",
            field=models.CharField(),
        ),
    ]
