# Generated by Django 4.2 on 2023-06-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartment", "0045_alter_apartmentinspection_inspection_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="maintainance",
            old_name="maintainance_category",
            new_name="maintenance_category",
        ),
        migrations.RenameField(
            model_name="maintainance",
            old_name="maintainance_type",
            new_name="maintenance_type",
        ),
        migrations.AlterField(
            model_name="apartmentinspection",
            name="inspection_time",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="maintainance",
            name="time_of_complaint",
            field=models.CharField(max_length=30),
        ),
    ]
