# Generated by Django 4.2 on 2023-06-02 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "apartment",
            "0047_apartmentbooking_cover_photo_apartmentbooking_email_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="tax_price",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="tax",
            field=models.DecimalField(decimal_places=1, default=7.5, max_digits=10),
        ),
    ]
