# Generated by Django 4.2 on 2023-06-05 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("apartment", "0048_apartment_tax_price_alter_apartment_tax"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintainance",
            name="apartment_id",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="apartment.apartment",
            ),
            preserve_default=False,
        ),
    ]
