# Generated by Django 4.2 on 2023-06-06 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartment", "0050_alter_maintainance_time_of_complaint"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="type_of_space",
            field=models.CharField(default="One Bedroom", max_length=40),
        ),
    ]
