# Generated by Django 4.2 on 2023-06-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartment", "0051_apartment_type_of_space"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartmentbooking",
            name="no_of_guests",
            field=models.IntegerField(default=1),
        ),
    ]
