# Generated by Django 4.2 on 2023-06-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartment", "0052_apartmentbooking_no_of_guests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintainance",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
