# Generated by Django 4.2 on 2023-06-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartment", "0053_alter_maintainance_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="owner_id",
            field=models.CharField(
                default="owner ID", help_text="Apartment owner ID", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="apartment",
            name="owner_name",
            field=models.CharField(
                default="owner name", help_text="Apartment owner name", max_length=255
            ),
        ),
    ]
