# Generated by Django 4.2 on 2023-06-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0055_apartment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='number_of_bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apartment',
            name='number_of_toilets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apartmentreview',
            name='user_photo',
            field=models.CharField(default='user photo'),
        ),
        migrations.AddField(
            model_name='apartmentreview',
            name='username',
            field=models.CharField(default='username'),
        ),
    ]
