# Generated by Django 4.2 on 2023-08-12 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0057_rename_maintainance_maintenance_apartment_image1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='images',
        ),
    ]
