# Generated by Django 4.2 on 2023-08-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0058_remove_apartment_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='apartment-images/'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='apartment-images/'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='apartment-images/'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='apartment-images/'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='apartment-images/'),
        ),
    ]
