# Generated by Django 4.2 on 2023-08-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0059_alter_apartment_image1_alter_apartment_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='country',
        ),
        migrations.AddField(
            model_name='apartment',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
