# Generated by Django 4.2 on 2023-08-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0063_rename_amenities_apartmentamenities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='credit_renting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartment',
            name='has_master_bedroom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartment',
            name='shared_housing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='cancellation_policy',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
