# Generated by Django 4.2 on 2023-08-22 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0065_saftyandsecurity_apartment_safty_and_security'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='lga',
        ),
    ]
